/******************************************************************************
* File Name: secure_keys.h
*
* Description: This file contains configuration parameters for the secure HTTP
* server and the server security keys such as server certificate, private key,
* and the root CA (certificate authority) to trust the client.
*
* Related Document: See README.md
*******************************************************************************
* Copyright 2020-2023, Cypress Semiconductor Corporation (an Infineon company) or
* an affiliate of Cypress Semiconductor Corporation.  All rights reserved.
*
* This software, including source code, documentation and related
* materials ("Software") is owned by Cypress Semiconductor Corporation
* or one of its affiliates ("Cypress") and is protected by and subject to
* worldwide patent protection (United States and foreign),
* United States copyright laws and international treaty provisions.
* Therefore, you may use this Software only as provided in the license
* agreement accompanying the software package from which you
* obtained this Software ("EULA").
* If no EULA applies, Cypress hereby grants you a personal, non-exclusive,
* non-transferable license to copy, modify, and compile the Software
* source code solely for use in connection with Cypress's
* integrated circuit products.  Any reproduction, modification, translation,
* compilation, or representation of this Software except as specified
* above is prohibited without the express written permission of Cypress.
*
* Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF ANY KIND,
* EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, NONINFRINGEMENT, IMPLIED
* WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. Cypress
* reserves the right to make changes to the Software without notice. Cypress
* does not assume any liability arising out of the application or use of the
* Software or any product or circuit described in the Software. Cypress does
* not authorize its products for use in any products where a malfunction or
* failure of the Cypress product may reasonably be expected to result in
* significant property damage, injury or death ("High Risk Product"). By
* including Cypress's product in a High Risk Product, the manufacturer
* of such system or application assumes all risk of such use and in doing
* so agrees to indemnify Cypress against all liability.
*******************************************************************************/

/*******************************************************************************
* Include guard
*******************************************************************************/
#ifndef SECURE_KEYS_H_
#define SECURE_KEYS_H_

/* HTTPS server certificate. Copy from the HTTPS server certificate
 * generated by OpenSSL (See Readme.md on how to generate a SSL certificate).
 */
#define keySERVER_CERTIFICATE_PEM \
"-----BEGIN CERTIFICATE-----\n"\
"MIICMjCCAdigAwIBAgIUD78icJre01RbESAlSEGKdFXFAOUwCgYIKoZIzj0EAwIw\n"\
"dzELMAkGA1UEBhMCVVMxEDAOBgNVBAgMB01vbnRhbmExEDAOBgNVBAcMB0JvemVt\n"\
"YW4xCzAJBgNVBAoMAkNZMRQwEgYDVQQLDAtFbmdpbmVlcmluZzEhMB8GA1UEAwwY\n"\
"bXlzZWN1cmVodHRwc2VydmVyLmxvY2FsMB4XDTI0MDMyMTAwNDk1NloXDTI2MTIx\n"\
"NjAwNDk1NlowdzELMAkGA1UEBhMCVVMxEDAOBgNVBAgMB01vbnRhbmExEDAOBgNV\n"\
"BAcMB0JvemVtYW4xCzAJBgNVBAoMAkNZMRQwEgYDVQQLDAtFbmdpbmVlcmluZzEh\n"\
"MB8GA1UEAwwYbXlzZWN1cmVodHRwc2VydmVyLmxvY2FsMFkwEwYHKoZIzj0CAQYI\n"\
"KoZIzj0DAQcDQgAEHIVlHw9vCHnGi4iLbQBd8PGQXjolS2cPqcG8mk+ozHtC+E12\n"\
"afM0s1phWtATJn9y1Yw8+UwBapJup1EzOleMy6NCMEAwHQYDVR0OBBYEFISN/Bnq\n"\
"UFJsn6/FyibPuSna1ZFyMB8GA1UdIwQYMBaAFCZg3XPjGgWP+Q8AsVsC9wrlmA8r\n"\
"MAoGCCqGSM49BAMCA0gAMEUCIG8qaASPoCwQO7Bt+8BwqbhDNlxsF9KTCcQYXAaS\n"\
"lAdTAiEAvNC2ZCQBkOPaIy70sN4cmg9sdCJqmGtuwMpsR8fAiWI=\n"\
"-----END CERTIFICATE-----"

/* Private key of the HTTPS server. Copy from the HTTPS server key
 * generated by OpenSSL (See Readme.md on how to create a private key).
 */
#define keySERVER_PRIVATE_KEY_PEM \
"-----BEGIN EC PRIVATE KEY-----\n"\
"MHcCAQEEICIXJvSfcH1kHmjm7EljRsL6kTy+o4TbPRJICdxqry6soAoGCCqGSM49\n"\
"AwEHoUQDQgAEHIVlHw9vCHnGi4iLbQBd8PGQXjolS2cPqcG8mk+ozHtC+E12afM0\n"\
"s1phWtATJn9y1Yw8+UwBapJup1EzOleMyw==\n"\
"-----END EC PRIVATE KEY-----"

/* HTTPS client certificate. In this example this is the RootCA
 * certificate so as to verify the HTTPS client's identity. */
#define keyCLIENT_ROOTCA_PEM \
"-----BEGIN CERTIFICATE-----\n"\
"MIICQjCCAemgAwIBAgIUaw4bp1afDOttMeUluExDEkx65dMwCgYIKoZIzj0EAwIw\n"\
"dzELMAkGA1UEBhMCVVMxEDAOBgNVBAgMB01vbnRhbmExEDAOBgNVBAcMB0JvemVt\n"\
"YW4xCzAJBgNVBAoMAkNZMRQwEgYDVQQLDAtFbmdpbmVlcmluZzEhMB8GA1UEAwwY\n"\
"bXlzZWN1cmVodHRwc2VydmVyLmxvY2FsMB4XDTI0MDMyMTAwNDk1NloXDTI0MDQy\n"\
"MDAwNDk1NlowdzELMAkGA1UEBhMCVVMxEDAOBgNVBAgMB01vbnRhbmExEDAOBgNV\n"\
"BAcMB0JvemVtYW4xCzAJBgNVBAoMAkNZMRQwEgYDVQQLDAtFbmdpbmVlcmluZzEh\n"\
"MB8GA1UEAwwYbXlzZWN1cmVodHRwc2VydmVyLmxvY2FsMFkwEwYHKoZIzj0CAQYI\n"\
"KoZIzj0DAQcDQgAEw4vtQFi0OUmY64NiYxT6Dm90UjRm58egfPT2PGpSNFUMjVKe\n"\
"i2qLD7UYdgIwcG94hCAxesJM4c5/L8PJ4GmfF6NTMFEwHQYDVR0OBBYEFCZg3XPj\n"\
"GgWP+Q8AsVsC9wrlmA8rMB8GA1UdIwQYMBaAFCZg3XPjGgWP+Q8AsVsC9wrlmA8r\n"\
"MA8GA1UdEwEB/wQFMAMBAf8wCgYIKoZIzj0EAwIDRwAwRAIgFm3sFxfNXXUK6tmu\n"\
"PYJRsHPqrhQv3osneWD+Fv/EBEsCIEbZordfZ7i7FxnWElUgRKuIxkAaAbyTX1KG\n"\
"u8ZkSNjG\n"\
"-----END CERTIFICATE-----"

#endif /* SECURE_KEYS_H_ */

/* [] END OF FILE */
